apiVersion: v2
name: django-angular-boilerplate-staging
description: Deployment manifest for django-angular-boilerplate in staging
type: application
version: 0.1.0
appVersion: "0.0.0"
dependencies:
  - name: django-angular-boilerplate
    alias: service
    version: 0.0.0-seed
    repository: oci://01234567890.dkr.ecr.us-west-1.amazonaws.com/helm
